### ISSUE TITLE
[suggestion] [docs] Colour of Section Headers

### ISSUE THREAD

**Issue by kumarharsh** [d10/lodash-docs-experiment#3]
[Migrated from https://github.com/lodash/lodash/issues/829]

I recently noticed that the documentation had had its colour theme changed. I've tried to work with it for a few hours, but the purple colour of the section header keeps distracting the eyes away from the actual documentation. Can it be changed to something more neutral?

The white earlier had been OK in that sense.

**Comment by jdalton** [comment]
Still open to suggestions here.

**Comment by d10** [comment]
Shifted to https://github.com/lodash/lodash.github.io/issues/10.
