### ISSUE TITLE
Empty footer element

### ISSUE THREAD

**Issue by d10** [d10/lodash-docs-experiment#7]
After the lodash v3 update, the site currently has an empty footer element.

**Comment by jdalton** [comment]
It's by design. I'm going with the less is more thing.

**Comment by jdalton** [comment]
Was this to update the experimental docs to align or as a bug report on the site?

**Comment by d10** [comment]
I was wondering whether it was intended, as the `footer` element still existed despite it being empty. I’m fine with removing it though.

**Comment by jdalton** [comment]
Empty but still styled. I like the look of it at least.
