### ISSUE TITLE
Intro `pre` block

### ISSUE THREAD

**Issue by d10** [d10/lodash-docs-experiment#9]
<img src=https://cloud.githubusercontent.com/assets/813865/6348774/2a7e3af8-bc5e-11e4-8353-6879b7f4d6f8.jpg height=40% width=40%>

@jdalton any reason why you need to allow overflowing for this `pre` block?

**Comment by jdalton** [comment]
overflow-x should be hidden.

**Comment by jdalton** [comment]
Hmm it was set to visible. I changed it to hidden.

**Comment by d10** [comment]
Why not just leave in the scroll functionality?

**Comment by jdalton** [comment]
The the scrollbar shows up in mobile IE.
